services:
  postgres:
    image: postgres:16-alpine
    container_name: birthday-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: birthday_service
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d birthday_service']
      interval: 5s
      timeout: 3s
      retries: 20

  localstack:
    image: localstack/localstack:3.8
    container_name: birthday-localstack
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: ap-southeast-2
      DEBUG: 0
    ports:
      - '4566:4566'
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  localstack_data:
